### ISSUE TITLE
[SR] Software Requirements (1~6)

### ISSUE THREAD

**Issue by charlie-lyc** [codestates/Missing_Animal_Client#7]
### ISSUE
- Group:  `sr`
- Type: `specification`
- Detail: Software Requirements 작성하기 

### TODO
1. [x] 프로젝트 선정
2. [x] 팀장, 팀명, 프로젝트명 정하기
3. [x] 팀원별 역할 설정
4. [x] 프로젝트 기획 및 범위 설정
5. [x] 시스템 아키텍쳐 설계
6. [x] 컴포넌트 구성

### Labels
- Estimated time: `E: 2h`
- Group : `sr`
- Urgency: `High`
