### ISSUE TITLE
[SR] Software Requirements (7~11) 

### ISSUE THREAD

**Issue by charlie-lyc** [codestates/Missing_Animal_Client#8]
### ISSUE
- Group:  `sr`
- Type: `specification`
- Detail: Software Requirements 작성하기 

### TODO
7. [x] 데이터베이스 스키마 작성
8. [x] API 문서 작성
9. [x] 프로젝트 태스크 카드 작성 & 분배
10. [x] 마일스톤 작성
11. [x] 팀 룰 작성

### Labels
- Estimated time: `E: 2h`
- Group : `sr`
- Urgency: `High`
